name: Push tag release

on:
  push:
    tags:
      - v[0-9].[0-9]+.[0-9]+

jobs:
  get-version-from-tag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
      - name: Print info about the version
        run: echo Version ${{ steps.get_version.outputs.VERSION }}

  cd:
    needs: get-version-from-tag
    uses: Approxoft/SvgBlazor/.github/workflows/base-workflow.yml@main
    with:
      publish-nuget: true
      version: ${{ needs.get-version-from-tag.outputs.version }}
    secrets:
      nuget-api-key: ${{ secrets.NUGET_API_KEY }}
